# Generated by Django 3.0.7 on 2021-09-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
