# Generated by Django 3.2.6 on 2021-09-23 13:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_auto_20210923_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('job_image', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='jobs/')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_location', models.CharField(blank=True, max_length=255, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('company_email', models.CharField(blank=True, max_length=255, null=True)),
                ('jobs_desc', models.TextField(blank=True, max_length=255, null=True)),
                ('jobs_required', models.IntegerField(blank=True, default=1, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter', to='users.lecture')),
                ('jobs_tags', models.ManyToManyField(blank=True, to='jobs.Need')),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('description', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('applicant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='recruits', to='users.student')),
                ('jobpost', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='jobs.jobpost')),
            ],
            options={
                'ordering': ['-date_applied', '-updated'],
            },
        ),
    ]
