# Generated by Django 3.2.6 on 2021-09-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='description',
        ),
    ]
